openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8443
  description: Generated server url
paths:
  /api/refresh:
    post:
      tags:
      - rest-login-controller
      summary: Checks if the user logged in is the same as the user in the token
      operationId: refreshToken
      parameters:
      - name: refreshToken
        in: cookie
        required: false
        schema:
          type: string
      responses:
        "403":
          description: Forbidden
          content:
            application/json: {}
        "200":
          description: User is logged in
          content:
            application/json: {}
        "401":
          description: Unauthorized
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json: {}
  /api/logout:
    post:
      tags:
      - rest-login-controller
      summary: Logs out the user
      operationId: logOut
      responses:
        "200":
          description: User is logged out
          content:
            application/json: {}
  /api/login:
    post:
      tags:
      - rest-login-controller
      summary: User login through form
      operationId: loginForm_1
      parameters:
      - name: accessToken
        in: cookie
        required: false
        schema:
          type: string
      - name: refreshToken
        in: cookie
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: User logged in successfully
          content:
            application/json: {}
        "403":
          description: Forbidden
          content:
            application/json: {}
        "401":
          description: Unauthorized
          content:
            application/json: {}
        "400":
          description: Bad request
          content:
            application/json: {}
  /api/accounts:
    get:
      tags:
      - rest-account-controller
      summary: Get all accounts
      operationId: getAllAccounts
      responses:
        "400":
          description: Bad request
        "404":
          description: Account Repository not found
        "500":
          description: Internal server error
        "200":
          description: Found the form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    post:
      tags:
      - rest-account-controller
      summary: Create New Account
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
        required: true
      responses:
        "200":
          description: Account Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "400":
          description: Bad request
        "404":
          description: Account not Found
        "500":
          description: Internal server error
  /api/accounts/{id}/transfers:
    get:
      tags:
      - rest-transfer-controller
      summary: Get all user transfers
      operationId: getAllUserTransfer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "400":
          description: Bad request
        "200":
          description: Found the form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        "404":
          description: Transfer Repository not found
        "500":
          description: Internal server error
    post:
      tags:
      - rest-transfer-controller
      summary: Make an user transfer
      operationId: createTransfer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
        required: true
      responses:
        "400":
          description: Bad request
        "404":
          description: Transfer Repository not found
        "500":
          description: Internal server error
        "200":
          description: transfer success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
  /api/accounts/{id}/loans:
    get:
      tags:
      - rest-loan-controller
      summary: Get paginated user loans
      operationId: getAllUserLoans
      parameters:
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad request
        "200":
          description: Found the loans
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Loan'
        "500":
          description: Internal server error
        "404":
          description: Loan Repository not found
    post:
      tags:
      - rest-loan-controller
      summary: Calculate a loan for user
      operationId: createLoan
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Loan'
        required: true
      responses:
        "400":
          description: Bad request
        "500":
          description: Internal server error
        "200":
          description: transfer success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        "404":
          description: Loan Repository not found
  /api/accounts/{accountId}/image:
    get:
      tags:
      - rest-account-controller
      operationId: getImage
      parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad request
        "404":
          description: Form not found
        "200":
          description: Get Image by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "500":
          description: Internal server error
    post:
      tags:
      - rest-account-controller
      summary: Upload image by ID
      operationId: uploadImage
      parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - imageFile
              type: object
              properties:
                imageFile:
                  type: string
                  format: binary
      responses:
        "400":
          description: Bad request
        "404":
          description: Form not found
        "500":
          description: Internal server error
        "200":
          description: Found the form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    delete:
      tags:
      - rest-account-controller
      summary: Delete an image by id
      operationId: deleteImage
      parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad request
        "404":
          description: Image not found
        "500":
          description: Internal server error
        "200":
          description: Image Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /transfers_manager_load:
    get:
      tags:
      - transfers-manager-controller
      operationId: transferManager
      parameters:
      - name: startIndex
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: chunkSize
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'
  /profile_data:
    get:
      tags:
      - profile-controller
      operationId: getTransferData
      parameters:
      - name: startIndex
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: chunkSize
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessedTransfer'
  /load-dynamic-content:
    get:
      tags:
      - dynamic-content-controller
      operationId: loadDynamicContent
      parameters:
      - name: client_iban
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /image_loader:
    get:
      tags:
      - profile-controller
      operationId: downloadImage
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
                  format: byte
  /data:
    get:
      tags:
      - loan-request-controller
      operationId: getLoanData
      parameters:
      - name: startIndex
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: chunkSize
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: number
                    format: float
  /api/transfers:
    get:
      tags:
      - rest-transfer-controller
      summary: Get all transfers
      operationId: getAllTransfer
      parameters:
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "400":
          description: Bad request
        "200":
          description: Found the form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        "404":
          description: Transfer Repository not found
        "500":
          description: Internal server error
  /api/transfers/{id}:
    get:
      tags:
      - rest-transfer-controller
      summary: Get a Transfer by ID
      operationId: getTransfer
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Bad request
        "404":
          description: Form not found
        "500":
          description: Internal server error
        "200":
          description: Found the Transfer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
  /api/accounts/{id}:
    get:
      tags:
      - rest-account-controller
      summary: Get an account by id
      operationId: getAccount
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad request
        "500":
          description: Internal server error
        "404":
          description: Account not found
        "200":
          description: Found the Account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDTO'
  /api/accounts/paged:
    get:
      tags:
      - rest-account-controller
      summary: Get paginated accounts
      operationId: getAllAccountsPaged
      parameters:
      - name: page
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'
      responses:
        "400":
          description: Bad request
        "404":
          description: Account Repository not found
        "500":
          description: Internal server error
        "200":
          description: Found the accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImagelessAccount'
  /account_load:
    get:
      tags:
      - account-controller
      operationId: accountManager
      parameters:
      - name: startIndex
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: chunkSize
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDTO'
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    CreateAccountRequest:
      type: object
      properties:
        inputUser:
          type: string
        name:
          type: string
        surname:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
    Account:
      type: object
      properties:
        account_id:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        balance:
          type: integer
          format: int32
        imageFile:
          type: object
          properties:
            binaryStream:
              type: object
        nip:
          type: string
        iban:
          type: string
    Transfer:
      type: object
      properties:
        transfer_id:
          type: integer
          format: int64
        senderIBAN:
          type: string
        receiverIBAN:
          type: string
        amount:
          type: integer
          format: int32
        date:
          type: string
        transferType:
          type: string
    Loan:
      type: object
      properties:
        loan_id:
          type: integer
          format: int64
        amount:
          type: integer
          format: int32
        interest_rate:
          type: number
          format: float
        periods:
          type: integer
          format: int32
        date:
          type: string
        loanPayments:
          type: array
          items:
            $ref: '#/components/schemas/LoanPayment'
        clientID:
          type: string
    LoanPayment:
      type: object
      properties:
        period:
          type: integer
          format: int32
        principal:
          type: number
          format: float
        interest:
          type: number
          format: float
        remainingAmount:
          type: number
          format: float
    ProcessedTransfer:
      type: object
      properties:
        transfer_id:
          type: integer
          format: int64
        clientIBAN:
          type: string
        senderIBAN:
          type: string
        receiverIBAN:
          type: string
        amount:
          type: integer
          format: int32
        date:
          type: string
        transferType:
          type: string
    Pageable:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
    Sort:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean
    AccountDTO:
      type: object
      properties:
        nip:
          type: string
        iban:
          type: string
        name:
          type: string
        surname:
          type: string
        imageBase64:
          type: string
    ImagelessAccount:
      type: object
      properties:
        nip:
          type: string
        iban:
          type: string
        name:
          type: string
        surname:
          type: string
